import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="flex flex-col min-h-screen bg-gray-50">
                    {/* Header */}
                    <header className="bg-black text-white py-6">
                        <div className="max-w-7xl mx-auto flex justify-between items-center">
                            <h1 className="text-3xl font-semibold">Fashion Stylist</h1>
                            <nav>
                                <ul className="flex space-x-6">
                                    <li><a href="/" className="hover:text-gray-400">Home</a></li>
                                    <li><a href="/about" className="hover:text-gray-400">About</a></li>
                                    <li><a href="/services" className="hover:text-gray-400">Services</a></li>
                                    <li><a href="/shop" className="hover:text-gray-400">Shop</a></li>
                                    <li><a href="/contact" className="hover:text-gray-400">Contact</a></li>
                                </ul>
                            </nav>
                        </div>
                    </header>

                    {/* Main Content */}
                    <main className="flex-1">{children}</main>

                    {/* Footer */}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
